---
name: "JellyfinStrmExtract"
guid: "5b9adc74-c34c-41bb-b8da-bbccd9e72455"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Extracts automatically info from STRM"
description: >
  This plugins extracts automatically media information from STRM files
category: "General"
owner: "gauthier-th"
artifacts:
- "JellyfinStrmExtract.dll"
changelog: >
  changelog
